// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njkihcrloqtgnomhlpig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qa2loY3Jsb3F0Z25vbWhscGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTAwNTUsImV4cCI6MjA3MzEyNjA1NX0.82JduTKRQ5WuIppAjwWcvrFOk8xs2auya4QUz9LTIOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});